### ISSUE TITLE
"sshd_config" template definition causes an error when no Match parameter is provided

### ISSUE THREAD

**Issue by dosyfier** [sous-chefs/openssh#106]
### Cookbook version
2.4.1

### Chef-client version
12.19.36

### Platform Details
RedHat 7.3

### Scenario:
When running OpenSSH cookbook default recipe, "sshd_config" template definition causes an error when no Match parameter is provided.

### Steps to Reproduce:
- Re-define default value of the whole `node['openssh']['server']` hash, e.g. by doing the following before including OpenSSH cookbook default recipe:
```
node.default['openssh']['server'] = {
  'x11_forwarding': 'yes',
  'log_level': 'INFO',
  ...
}
```
without specifying the "match" parameter, which should thus be left equal to `nil`.
- Include and run OpenSSH cookbook default recipe.

### Expected Result:
No "Match XXX" entry is added into /etc/ssh/sshd_config.

### Actual Result:
Chef terminates in error (see stack trace below).

A possible enhancement of the cookbook would be to invert and modify "unless" conditions in templates/default/sshd_config.erb, l. 14:
- currently:
`<%  unless node['openssh']['server']['match'].empty? || !defined?(node['openssh']['server']['match']) -%>`
- modified:
`<%  unless node['openssh']['server']['match'].nil? || node['openssh']['server']['match'].empty? -%>`

Stacktrace:
```
    ================================================================================
    Error executing action `create` on resource 'template[/etc/ssh/sshd_config]'
    ================================================================================

    Chef::Mixin::Template::TemplateError
    ------------------------------------
    undefined method `empty?' for nil:NilClass

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/openssh/recipes/default.rb

     46: template '/etc/ssh/sshd_config' do
     47:   source 'sshd_config.erb'
     48:   mode node['openssh']['config_mode']
     49:   owner 'root'
     50:   group node['root_group']
     51:   variables(options: openssh_server_options)
     52:   notifies :run, 'execute[sshd-config-check]', :immediately
     53:   notifies :restart, 'service[ssh]'
     54: end
     55:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/openssh/recipes/default.rb:46:in `from_file'

    template("/etc/ssh/sshd_config") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      source "sshd_config.erb"
      variables {:options=>[["allow_tcp_forwarding", "no"], ["allows_groups", "_ccs_administrateurs_systeme _ccs_super_operateurs"], ["listen_address", ["172.16.131.57", "172.16.131.59"]], ["login_grace_time", "30"], ["max_auth_tries", "2"], ["permit_user_environment", "no"], ["print_last_log", "yes"], ["x11_forwarding", "yes"]]}
      declared_type :template
      cookbook_name "openssh"
      recipe_name "default"
      owner "root"
      group "root"
      mode "0600"
      path "/etc/ssh/sshd_config"
      verifications []
    end

    Template Context:
    -----------------
    on line #14
     12: <% end -%>
     13:
     14: <%  unless node['openssh']['server']['match'].empty? || !defined?(node['openssh']['server']['match']) -%>
     15: <%    node['openssh']['server']['match'].sort.map do |match_key, match_items| -%>
     16: Match <%= match_key %>

    Platform:
    ---------
    x86_64-linux
```

**Comment by donwlewis** [comment]
@dosyfier I attempted you fix, but I still get the same error.

**Comment by dosyfier** [comment]
@donwlewis Yes, I think I got it wrong about the behavior of Ruby's `defined?` method.
And I just realized the `node['openssh']['server']['match']` attribute was actually set in attributes/default.rb file to `{}`.

The actual problem was that, calling OpenSSH cookbook in my own recipe, I re-configured the whole `node['openssh']['server']` hash:
```
node.default['openssh']['server'] = {
  'x11_forwarding': 'yes',
  'log_level': 'INFO',
  ...
}
```
thus erasing that setting `node['openssh']['server']['match'] = {}` done within attributes/default.rb.

I'll edit the issue in consequence: an enhancement of the sshd_config template would be to check whether this "match" attribute is `nil` or not.

**Comment by donwlewis** [comment]
As a workaround, I added `   'match' => ''` to my `default['openssh']['server']` hash.

**Comment by tdgeery** [comment]
+1 on this.

Getting an error similar to this:

`resource template[/etc/ssh/sshd_config] is configured to notify resource execute[sshd-config-check] with action run, but execute[sshd-config-check] cannot be found in the resource`
