### ISSUE TITLE
CentOS 8 fails with "No such file or directory - /usr/sbin/sshd-keygen"

### ISSUE THREAD

**Issue by msgarbossa** [sous-chefs/openssh#139]
Cookbook version
2.9.0

Chef-client version
17.0.157

Platform Details
CentOS 8.3.2011

Scenario:
The CentOS platform_version comparison in the library is broken when converting 8.3.2011 to an integer 

Steps to Reproduce:
Run kitchen test with CentOS 8 dokken image.

Expected Result:
/usr/libexec/openssh/sshd-keygen should be executed because /usr/sbin/sshd-keygen does not exist.

Actual Result:
cookbook executes /usr/sbin/sshd-keygen, which does not exist.

```
  * execute[/usr/sbin/sshd-keygen] action run

    ================================================================================
    Error executing action `run` on resource 'execute[/usr/sbin/sshd-keygen]'
    ================================================================================

    Errno::ENOENT
    -------------
    No such file or directory - /usr/sbin/sshd-keygen

    Resource Declaration:
    ---------------------
    # In /opt/kitchen/cache/cookbooks/openssh/recipes/default.rb

     69:     execute '/usr/sbin/sshd-keygen'
     70:   end

    Compiled Resource:
    ------------------
    # Declared in /opt/kitchen/cache/cookbooks/openssh/recipes/default.rb:69:in `from_file'

    execute("/usr/sbin/sshd-keygen") do
      action [:run]
      default_guard_interpreter :execute
      command "/usr/sbin/sshd-keygen"
      declared_type :execute
      cookbook_name "openssh"
      recipe_name "default"
      domain nil
      user nil
    end

    System Info:
    ------------
    chef_version=17.0.157
    platform=centos
    platform_version=8.3.2011
    ruby=ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
    program_name=/opt/chef/bin/chef-client
    executable=/opt/chef/bin/chef-client
```

**Comment by msgarbossa** [comment]
@ramereth For some reason on CentOS 8 it was trying to execute /usr/sbin/sshd-keygen instead of /usr/libexec/openssh/sshd-keygen in this [block](https://github.com/sous-chefs/openssh/blob/master/recipes/default.rb#L62-L73).  I suspected there might be an issue converting from a semantic version to an integer instead of from a float to an integer, which is why I tested the string parsing the way I did.  I created  the sample ruby file below, which proves the current code works correctly to parse semantic versions without the split.

```
$ cat test.rb
# versions
platform_version_float="8.2"
platform_version_semver="8.3.2011"

# test float to integer
platform_version_float2int = platform_version_float.to_i
print "#{platform_version_float2int}\n"

# test semver to integer
platform_version_semver2int = platform_version_semver.to_i
print "#{platform_version_semver2int}\n"
```

```
$ /opt/chef-workstation/embedded/bin/ruby test.rb
8
8
```

We're more RHEL-centric and there isn't a dokken image for RHEL 8 so I'm having a difficult time testing w/ CentOS 8.   dokken/centos-7 seemed to be a better substitute for RHEL 7 for testing purposes than CentOS 8 and RHEL 8.  I'm pretty sure I'm dealing with repo issues.  I can't explain why the change I made to my local copy of this cookbook seemed to fix my issue.   I agree with your assessment that this shouldn't have anything to do with it.  No change needed.

**Comment by ramereth** [comment]
Does this problem still happen with Chef 16 on your system? I might try doing a test on a proper RHEL 8 system to see if it happens there but I'm still confused as to why it would be doing that.

**Comment by msgarbossa** [comment]
I can't even reproduce this anymore and it's working with my change backed out.  It works in kitchen and a proper RHEL 8 VM.  Also works w/ Chef 16 and 17.   I'm chalking this up to a package repo issue based on other errors I was getting around this time.  Thanks for helping out.  I appreciate the work on this cookbook.
